name:                tvmv
version:             0.3.0
github:              "keithfancher/tvmv"
license:             BSD3
author:              "Keith Fancher"
maintainer:          "nospam@example.com"
copyright:           "2022 Keith Fancher"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/keithfancher/tvmv#readme>

dependencies:
- base >= 4.7 && < 5
- text
- directory
- filepath

language: GHC2021 # the future!

default-extensions:
- DuplicateRecordFields
- LambdaCase
- OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - themoviedb
  - mtl
  - parsec
  - time
  - word-wrap
  - containers

executables:
  tvmv:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tvmv
    - optparse-applicative

tests:
  unit:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tvmv
    - hspec
    - themoviedb
  integration:
    main:                Spec.hs
    source-dirs:         test/integration
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tvmv
    - hspec
